# Generated by Django 4.2.29 on 2026-04-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
